packages:
  - 'packages/*'

catalogs:
  devtools:
    vite-plus: ^0.1.19
    bumpp: ^11.0.1
    changelogithub: ^14.0.0
    semver: ^7.7.4

  types:
    '@types/node': ^25.6.0
    typescript: ^6.0.3
    '@typescript/native-preview': latest

  oxlint:
    '@oxlint/plugins': ^1.62.0
