//! The definition of JavaScript related nodes
//!
//! ## Expressions
//!
//! We split `VExpressionContainer` into different kinds, but they are all serialized as `VExpressionContainer`
//! - VInterpolation: `{{ }}`, can be treated as a VNode.
//! - VDirectiveExpression: `v-bind`, `v-model`, `v-if` and most of the directives (including all custom directives).
//! - VOnExpression: `v-on`, used in `v-on` directive, with body to storage statements inside.
//! - VForExpression: `v-for`, used in `v-for` directive, with left and right to storage variable definitions and source.
//! - VSlotExpression: `v-slot`, used in `v-slot` directive, with params to storage variable definitions.
//!
//! We have to traverse nodes generated by oxc_parser as VExpressionContainer requires `references` field to trace variable bindings.

use oxc_allocator::Vec;
use oxc_ast::ast::{Expression, FormalParameters, Statement};
use oxc_span::Span;

use crate::ast::bindings::Reference;

#[derive(Debug)]
pub struct VInterpolation<'a> {
  pub expression: Expression<'a>,
  pub references: Vec<'a, Reference<'a>>,
  pub span: Span,
}

#[derive(Debug)]
pub struct VDirectiveExpression<'a> {
  pub expression: Expression<'a>,
  pub references: Vec<'a, Reference<'a>>,
  pub span: Span,
}

#[derive(Debug)]
pub struct VOnExpression<'a> {
  pub body: Vec<'a, Statement<'a>>,
  pub references: Vec<'a, Reference<'a>>,
  pub span: Span,
}

#[derive(Debug)]
pub struct VForExpression<'a> {
  pub left: FormalParameters<'a>,
  pub right: Expression<'a>,
  pub references: Vec<'a, Reference<'a>>,
  pub span: Span,
}

#[derive(Debug)]
pub struct VSlotExpression<'a> {
  pub params: FormalParameters<'a>,
  pub span: Span,
}

// TODO: impl Serialize (VExpressionContainer as the result) for all the nodes above
