//! The definition of JavaScript related nodes
//! Most of these nodes need needs 'b lifetime to make js related nodes storage in `js_allocator`
//!
//! ## Expressions
//!
//! We split `VExpressionContainer` into different kinds, but they are all serialized as `VExpressionContainer`
//! - `VInterpolation`: `{{ }}`, can be treated as a `VNode`.
//! - `VDirectiveExpression`: `v-bind`, `v-model`, `v-if` and most of the directives (including all custom directives).
//! - `VOnExpression`: `v-on`, used in `v-on` directive, with body to storage statements inside.
//! - `VForExpression`: `v-for`, used in `v-for` directive, with left and right to storage variable definitions and source.
//! - `VSlotExpression`: `v-slot`, used in `v-slot` directive, with params to storage variable definitions.
//!
//! We have to traverse nodes generated by `oxc_parser` as `VExpressionContainer` requires `references` field to trace variable bindings.
//!
//! ## Pure JS
//!
//! It's only used in <script> and <script setup> blocks.

use oxc_allocator::{Box, Vec};
use oxc_ast::ast::{Directive, Expression, FormalParameters, Statement};
use oxc_estree::{Concat2, ESTree, JsonSafeString, Serializer, StructSerializer};
use oxc_span::Span;

use crate::ast::bindings::Reference;

#[derive(Debug)]
pub struct VInterpolation<'a, 'b> {
  pub expression: Expression<'b>,
  pub references: Vec<'a, Reference<'a>>,
  pub span: Span,
}

#[derive(Debug)]
pub struct VDirectiveExpression<'a, 'b> {
  pub expression: Expression<'b>,
  pub references: Vec<'a, Reference<'a>>,
  pub span: Span,
}

#[derive(Debug)]
pub struct VDirectiveArgumentExpression<'a, 'b> {
  pub expression: Expression<'b>,
  pub references: Vec<'a, Reference<'a>>,
  pub span: Span,
}

#[derive(Debug)]
pub struct VOnExpression<'a, 'b> {
  pub body: Vec<'b, Statement<'b>>,
  pub references: Vec<'a, Reference<'a>>,
  pub span: Span,
}

#[derive(Debug)]
pub struct VForExpression<'a, 'b> {
  pub left: Box<'b, FormalParameters<'b>>,
  pub right: Expression<'b>,
  pub references: Vec<'a, Reference<'a>>,
  pub span: Span,
  pub expression_span: Span,
}

#[derive(Debug)]
pub struct VSlotExpression<'b> {
  pub params: Box<'b, FormalParameters<'b>>,
  // There shouldn't be references in slot expression
  pub span: Span,
  pub expression_span: Span,
}

#[derive(Debug)]
pub struct VPureScript<'b> {
  pub statements: Vec<'b, Statement<'b>>,
  pub directives: Vec<'b, Directive<'b>>,
  pub span: Span,
}

impl ESTree for VInterpolation<'_, '_> {
  fn serialize<S: Serializer>(&self, serializer: S) {
    let mut state = serializer.serialize_struct();
    state.serialize_field("type", &JsonSafeString("VExpressionContainer"));
    state.serialize_field("expression", &self.expression);
    state.serialize_field("references", &self.references);
    state.serialize_span(self.span);
    state.end();
  }
}

impl ESTree for VDirectiveExpression<'_, '_> {
  fn serialize<S: Serializer>(&self, serializer: S) {
    let mut state = serializer.serialize_struct();
    state.serialize_field("type", &JsonSafeString("VExpressionContainer"));
    state.serialize_field("expression", &self.expression);
    state.serialize_field("references", &self.references);
    state.serialize_span(self.span);
    state.end();
  }
}

impl ESTree for VDirectiveArgumentExpression<'_, '_> {
  fn serialize<S: Serializer>(&self, serializer: S) {
    let mut state = serializer.serialize_struct();
    state.serialize_field("type", &JsonSafeString("VExpressionContainer"));
    state.serialize_field("expression", &self.expression);
    state.serialize_field("references", &self.references);
    state.serialize_span(self.span);
    state.end();
  }
}

impl ESTree for VOnExpression<'_, '_> {
  fn serialize<S: Serializer>(&self, serializer: S) {
    // Define a temporary struct to hold the expression
    struct VOnExpression<'b> {
      body: &'b Vec<'b, Statement<'b>>,
      span: Span,
    }
    impl ESTree for VOnExpression<'_> {
      fn serialize<S: Serializer>(&self, serializer: S) {
        let mut state = serializer.serialize_struct();
        state.serialize_field("type", &JsonSafeString("VOnExpression"));
        state.serialize_field("body", self.body);
        state.serialize_span(self.span);
        state.end();
      }
    }

    let mut state = serializer.serialize_struct();
    state.serialize_field("type", &JsonSafeString("VExpressionContainer"));
    state.serialize_field("expression", &VOnExpression { body: &self.body, span: self.span });
    state.serialize_field("references", &self.references);
    state.serialize_span(self.span);
    state.end();
  }
}

impl ESTree for VForExpression<'_, '_> {
  fn serialize<S: Serializer>(&self, serializer: S) {
    // Define a temporary struct to hold the expression
    struct VForExpression<'b> {
      left: &'b FormalParameters<'b>,
      right: &'b Expression<'b>,
      span: Span,
    }
    impl ESTree for VForExpression<'_> {
      fn serialize<S: Serializer>(&self, serializer: S) {
        let mut state = serializer.serialize_struct();
        state.serialize_field("type", &JsonSafeString("VForExpression"));
        state.serialize_field("left", &self.left);
        state.serialize_field("right", &self.right);
        state.serialize_span(self.span);
        state.end();
      }
    }

    let mut state = serializer.serialize_struct();
    state.serialize_field("type", &JsonSafeString("VExpressionContainer"));
    state.serialize_field(
      "expression",
      &VForExpression { left: &self.left, right: &self.right, span: self.expression_span },
    );
    state.serialize_field("references", &self.references);
    state.serialize_span(self.span);
    state.end();
  }
}

impl ESTree for VSlotExpression<'_> {
  fn serialize<S: Serializer>(&self, serializer: S) {
    // Define a temporary struct to hold the expression
    struct VSlotExpression<'b> {
      params: &'b FormalParameters<'b>,
      span: Span,
    }
    impl ESTree for VSlotExpression<'_> {
      fn serialize<S: Serializer>(&self, serializer: S) {
        let mut state = serializer.serialize_struct();
        state.serialize_field("type", &JsonSafeString("VSlotScopeExpression"));
        state.serialize_field("params", &self.params);
        state.serialize_span(self.span);
        state.end();
      }
    }

    let mut state = serializer.serialize_struct();
    state.serialize_field("type", &JsonSafeString("VExpressionContainer"));
    state.serialize_field(
      "expression",
      &VSlotExpression { params: &self.params, span: self.expression_span },
    );
    state.serialize_field("references", &[(); 0]);
    state.serialize_span(self.span);
    state.end();
  }
}

// Will be transformed in toolkit side
impl ESTree for VPureScript<'_> {
  fn serialize<S: Serializer>(&self, serializer: S) {
    let mut state = serializer.serialize_struct();
    state.serialize_field("type", &JsonSafeString("VPureScript"));
    state.serialize_field("body", &Concat2(&self.directives, &self.statements));
    state.serialize_span(self.span);
    state.end();
  }
}
