/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface NativeComment {
  type: 'Line' | 'Block'
  value: string
  start: number
  end: number
  range: [number, number]
}

export interface NativeDiagnostic {
  message: string
  start: number
  end: number
}

export interface NativeMapping {
  virtualStart: number
  virtualEnd: number
  originalStart: number
  originalEnd: number
}

export declare function nativeParse(source: string): NativeParseResult

export interface NativeParseResult {
  astJson: string
  irregularWhitespaces: [number, number][]
  errors: Array<NativeDiagnostic>
  panicked: boolean
}

export declare function nativeTransformJsx(source: string): NativeTransformResult

export interface NativeTransformResult {
  sourceText: string
  scriptKind: 'jsx' | 'tsx'
  comments: Array<NativeComment>
  irregularWhitespaces: [number, number][]
  errors: Array<NativeDiagnostic>
  mappings: Array<NativeMapping>
}
