/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface NativeComment {
  type: 'Line' | 'Block'
  value: string
  start: number
  end: number
}

export interface NativeDiagnostic {
  message: string
  start: number
  end: number
}

export interface NativeMapping {
  virtualStart: number
  virtualEnd: number
  originalStart: number
  originalEnd: number
}

export interface NativeParseResult {
  astJson: string
  errors: Array<NativeDiagnostic>
  panicked: boolean
}

export interface NativeRange {
  start: number
  end: number
}

export interface NativeTransformResult {
  sourceText: string
  scriptKind: 'jsx' | 'tsx'
  comments: Array<NativeComment>
  irregularWhitespaces: Array<NativeRange>
  errors: Array<NativeDiagnostic>
  mappings: Array<NativeMapping>
}

export declare function parseVue(source: string): NativeParseResult

export declare function transformJsx(source: string): NativeTransformResult
