/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Parse a `.vue` SFC source string and return a JSON-serialised AST.
 *
 * The returned string is a JSON object of the form
 * `{ document: VDocumentFragment, scripts: ScriptJson[] }`. See
 * `vue_oxlint_parser::parser` for the schema details.
 *
 * # Errors
 * Returns a JS-side `Error` when the SFC layout is malformed.
 */
export declare function parseSync(source: string): string

export declare function plus100(input: number): number
